/**
 * Colourunder — browser demo.
 *
 * VHS's helical-scan colour-under recording. A VHS deck cannot record colour
 * at its broadcast frequency, so it heterodynes the chroma down under the
 * luma's FM carrier and back up on playback: chroma keeps about 40 lines of
 * resolution, arrives late, picks up band-limited blotches of noise, and its
 * playback phase error is a hue shift on NTSC and a desaturation on PAL. The
 * two heads on the spinning drum add the rest: the switch 6.5 lines before V
 * sync tears the bottom lines sideways, a tracking error walks a noise bar up
 * the picture, and missing oxide drops a line to white or, with DOC on, to a
 * repeat of the line 1H above.
 *
 * Like receipt and instant, this plugin is **not only a shader**, and the two
 * halves of the page are not equally faithful:
 *
 *   The shaders are the plugin's. The version line, the `kCommon` block and
 *   the eight bodies of `source/Shaders.cpp` (vertex, intakev, intakeh, noise,
 *   tape, comb, doc, display) are spliced into the generated block below by
 *   `demo/tools/sync_shaders.py`, tabs and comments included, and `assemble`
 *   below is Shaders.cpp's. `demo/tools/check_shaders.py --dump` compares
 *   every assembled stage with what the plugin compiles
 *   (`cutest --dump-shaders`); `tools/verify.sh` runs it.
 *
 *   The CPU half is a PORT. In the plugin every coefficient -- the nine
 *   kernels, the per-line tracking bar, noise gain and phase error (its cos
 *   and sin in double), the head switch and the AFC's recovery, the dropouts,
 *   the noise seeds, the clock -- is computed once a frame in C++ and handed
 *   over as uniforms and one RGBA32F texture. `demo/model.js` is a hand
 *   translation of that, and `demo/tools/check_port.sh` compares it with the
 *   plugin's own ProcessOpenGL and constructor, run under a recorder, value
 *   for value. This file's GL half (which WebGL object each name in the plan
 *   is, and the draws) only a reader checks.
 *
 * ------------------------------------------------------ the frame
 *
 *   plan      model.js: the settings, the clock, the kernels, LineData and
 *             every pass's uniforms (CPU, in double, floats where the plugin
 *             hands floats over)
 *   upload    LineData, N x 6 RGBA32F
 *   intakev   host rows onto the standard's 576 or 480 lines (N x W)
 *   intakeh   pixels onto the line raster's Ws samples (N x Ws)
 *   per generation, 1..5:
 *     noise   seeded white noise
 *     tape    the filters, the FM and chroma noise, the bar, the switching
 *             transient, the phase error, the dropouts
 *     comb    the 1H chroma average
 *     doc     the dropout compensator
 *   display   nearest line per row, Catmull-Rom across, the time-base
 *             displacement, Y'UV to R'G'B', Mix
 */

import { mountDemo } from './vendor/demo.js';
import { Program, PassBuffer, GLError, bindTexture } from './vendor/gl.js';
import {
  Instance, DECLARATIONS, PT, controls, kGenerationsMax, kGenerationsMin, kPAL, kNTSC, kSP, kEP, standardOf,
} from './model.js';

//=== BEGIN GENERATED by demo/tools/sync_shaders.py from source/Shaders.cpp -- do not edit by hand.

// source/Shaders.cpp, verbatim. `assemble` (below the block) is Shaders.cpp's.
const K_VERSION = "#version 410 core";

const VERTEX_BODY = `
layout( location = 0 ) in vec4 vPosition;
layout( location = 1 ) in vec2 vUV;

out vec2 uv;

void main()
{
	gl_Position = vPosition;
	uv = vUV;
}
`;

const COMMON = `
const float kUScale = 0.492111;
const float kVScale = 0.877283;

vec3 rgbToYuv( vec3 c )
{
	float y = 0.299 * c.r + 0.587 * c.g + 0.114 * c.b;
	return vec3( y, kUScale * ( c.b - y ), kVScale * ( c.r - y ) );
}

vec3 yuvToRgb( vec3 yuv )
{
	float r = yuv.x + yuv.z / kVScale;
	float b = yuv.x + yuv.y / kUScale;
	float g = ( yuv.x - 0.299 * r - 0.114 * b ) / 0.587;
	return vec3( r, g, b );
}

uint hashInt( uint v )
{
	uint state = v * 747796405u + 2891336453u;
	uint word  = ( ( state >> ( ( state >> 28u ) + 4u ) ) ^ state ) * 277803737u;
	return ( word >> 22u ) ^ word;
}

float hashUnit( uint h )
{
	return float( h >> 8u ) * ( 1.0 / 16777216.0 );
}
`;

const INTAKEV_BODY = `
uniform sampler2D Source;
uniform int HostH;
uniform int Lines;

out vec4 fragColor;

void main()
{
	ivec2 p   = ivec2( gl_FragCoord.xy );
	int lo    = p.y * HostH;
	int hi    = ( p.y + 1 ) * HostH;
	int first = lo / Lines;
	int last  = ( hi - 1 ) / Lines;
	vec4 sum  = vec4( 0.0 );
	for( int r = first; r <= last; ++r )
	{
		int overlap = min( ( r + 1 ) * Lines, hi ) - max( r * Lines, lo );
		vec4 c      = texelFetch( Source, ivec2( p.x, HostH - 1 - r ), 0 );
		sum += float( overlap ) * c;
	}
	fragColor = sum / float( HostH );
}
`;

const INTAKEH_BODY = `
uniform sampler2D Lines;
uniform int HostW;
uniform int K;
uniform int YFirst;
uniform int YCount;
uniform float YW[ 96 ];

out vec4 fragColor;

void main()
{
	ivec2 p  = ivec2( gl_FragCoord.xy );
	int base = p.x * K;
	float y  = 0.0;
	for( int n = 0; n < YCount; ++n )
	{
		int x = clamp( base + YFirst + n, 0, HostW - 1 );
		y += YW[ n ] * rgbToYuv( texelFetch( Lines, ivec2( x, p.y ), 0 ).rgb ).x;
	}
	vec2 c = vec2( 0.0 );
	for( int n = 0; n < K; ++n )
	{
		int x = clamp( base + n, 0, HostW - 1 );
		c += rgbToYuv( texelFetch( Lines, ivec2( x, p.y ), 0 ).rgb ).yz;
	}
	fragColor = vec4( y, c / float( K ), 1.0 );
}
`;

const NOISE_BODY = `
uniform int Samples;
uniform int LineCount;
uniform uint Seed;

out vec4 fragColor;

void main()
{
	ivec2 p = ivec2( gl_FragCoord.xy );
	uint at = uint( p.x ) + uint( Samples ) * uint( p.y );
	vec4 n;
	for( int c = 0; c < 4; ++c )
		n[ c ] = ( hashUnit( hashInt( at * 4u + uint( c ) + hashInt( Seed ) ) ) * 2.0 - 1.0 ) * 1.7320508;
	fragColor = n;
}
`;

const TAPE_BODY = `
uniform sampler2D Src;
uniform sampler2D NoiseTex;
uniform sampler2D LineData;
uniform int Samples;
uniform int Gen;          //this generation's row of LineData
uniform int Pal;

uniform int YFirst;       //luma: this generation's filter (identity in generation 1)
uniform int YCount;
uniform float YW[ 96 ];
uniform int CFirst;       //chroma: record and playback together, the group delay included
uniform int CCount;
uniform float CW[ 96 ];
uniform int NYFirst;      //the FM noise's shape
uniform int NYCount;
uniform float NYW[ 96 ];
uniform int NCFirst;      //the chroma noise: the playback filter alone
uniform int NCCount;
uniform float NCW[ 96 ];

uniform float LumaSigma;
uniform float ChromaSigma;
uniform int BurstLine;    //the field line the switch falls on, or -1
uniform float BurstStart; //the sample it falls at
uniform int BurstSamples;
uniform float BurstAmount;

uniform int DropCount;
uniform vec4 Drops[ 24 ]; //( line, first sample, end sample, 0 )

out vec4 fragColor;

ivec2 at( int x, int l )
{
	return ivec2( clamp( x, 0, Samples - 1 ), l );
}

void main()
{
	ivec2 p = ivec2( gl_FragCoord.xy );
	int l   = p.y;

	float y = 0.0;
	for( int n = 0; n < YCount; ++n )
		y += YW[ n ] * texelFetch( Src, at( p.x + YFirst + n, l ), 0 ).x;
	vec2 c = vec2( 0.0 );
	for( int n = 0; n < CCount; ++n )
		c += CW[ n ] * texelFetch( Src, at( p.x + CFirst + n, l ), 0 ).yz;

	float ny = 0.0;
	for( int n = 0; n < NYCount; ++n )
		ny += NYW[ n ] * texelFetch( NoiseTex, at( p.x + NYFirst + n, l ), 0 ).x;
	vec2 nc = vec2( 0.0 );
	for( int n = 0; n < NCCount; ++n )
		nc += NCW[ n ] * texelFetch( NoiseTex, at( p.x + NCFirst + n, l ), 0 ).yz;
	float raw = texelFetch( NoiseTex, p, 0 ).w;

	vec4 ld = texelFetch( LineData, ivec2( l, Gen ), 0 );
	y += LumaSigma * ld.x * ny;
	c += ChromaSigma * ld.x * nc;

	//The bar: where the head reads the wrong track the FM demodulator loses
	//lock and the picture is noise; the burst goes, and the colour killer
	//with it.
	y = mix( y, 0.5 + 0.3 * raw, ld.y );
	c *= 1.0 - ld.y;

	//The switching transient, from the switch instant.
	if( ( l >> 1 ) == BurstLine && float( p.x ) >= BurstStart && float( p.x ) < BurstStart + float( BurstSamples ) )
	{
		y = mix( y, 0.5 + 0.4 * raw, BurstAmount );
		c *= 1.0 - BurstAmount;
	}

	//The playback phase error, as its cosine and sine (computed in double on
	//the CPU: GLSL leaves sin and cos's precision to the driver, and Apple's
	//software renderer is 8e-4 rad out). PAL's V axis is inverted on
	//alternate lines of a field, so after the decoder puts it back the same
	//error turns the other way on the next line.
	float cs = ld.z, sn = ld.w;
	if( Pal != 0 && ( ( l >> 1 ) & 1 ) != 0 )
		sn = -sn;
	c = vec2( cs * c.x - sn * c.y, sn * c.x + cs * c.y );

	//Missing oxide: no carrier, a white streak, flagged for the compensator.
	float flag = 0.0;
	for( int i = 0; i < DropCount; ++i )
		if( int( Drops[ i ].x ) == l && float( p.x ) >= Drops[ i ].y && float( p.x ) < Drops[ i ].z )
			flag = 1.0;
	if( flag > 0.5 )
	{
		y = 0.92 + 0.05 * raw;
		c = vec2( 0.0 );
	}

	fragColor = vec4( y, c, flag );
}
`;

const COMB_BODY = `
uniform sampler2D Src;
uniform int Skip;

out vec4 fragColor;

void main()
{
	ivec2 p = ivec2( gl_FragCoord.xy );
	vec4 v  = texelFetch( Src, p, 0 );
	if( Skip == 0 && p.y >= 2 )
		v.yz = 0.5 * ( v.yz + texelFetch( Src, ivec2( p.x, p.y - 2 ), 0 ).yz );
	fragColor = v;
}
`;

const DOC_BODY = `
uniform sampler2D Src;
uniform int Enabled;
uniform int Step;

out vec4 fragColor;

void main()
{
	ivec2 p = ivec2( gl_FragCoord.xy );
	vec4 v  = texelFetch( Src, p, 0 );
	if( Enabled != 0 && v.w > 0.5 )
	{
		for( int k = 1; k <= 8; ++k )
		{
			int l = p.y - k * Step;
			if( l < 0 )
				break;
			vec4 u = texelFetch( Src, ivec2( p.x, l ), 0 );
			if( u.w < 0.5 )
			{
				v = u;
				break;
			}
		}
	}
	fragColor = vec4( v.xyz, 0.0 );
}
`;

const DISPLAY_BODY = `
uniform sampler2D Lines;
uniform sampler2D Source;
uniform sampler2D LineData;
uniform int HostW;
uniform int HostH;
uniform int LineCount;
uniform int Samples;
uniform int K;
uniform int TimeRow;
uniform float MixAmount;

in vec2 uv;
out vec4 fragColor;

vec3 tap( int i, int l )
{
	return texelFetch( Lines, ivec2( clamp( i, 0, Samples - 1 ), l ), 0 ).xyz;
}

void main()
{
	int x   = clamp( int( floor( uv.x * float( HostW ) ) ), 0, HostW - 1 );
	int rgl = clamp( int( floor( uv.y * float( HostH ) ) ), 0, HostH - 1 );
	int r   = HostH - 1 - rgl;
	int l   = ( ( 2 * r + 1 ) * LineCount ) / ( 2 * HostH );

	vec4 ld = texelFetch( LineData, ivec2( l, TimeRow ), 0 );
	float s = ( float( x ) - 0.5 * float( K - 1 ) ) / float( K );
	if( s >= ld.y )
		s -= ld.x;

	vec3 yuv = vec3( 0.0 );
	if( s >= -0.5 && s <= float( Samples ) - 0.5 )
	{
		float i0 = floor( s );
		float t  = s - i0;
		int i    = int( i0 );
		float t2 = t * t, t3 = t2 * t;
		float w0 = 0.5 * ( -t3 + 2.0 * t2 - t );
		float w1 = 0.5 * ( 3.0 * t3 - 5.0 * t2 + 2.0 );
		float w2 = 0.5 * ( -3.0 * t3 + 4.0 * t2 + t );
		float w3 = 0.5 * ( t3 - t2 );
		yuv = w0 * tap( i - 1, l ) + w1 * tap( i, l ) + w2 * tap( i + 1, l ) + w3 * tap( i + 2, l );
	}

	vec4 src  = texelFetch( Source, ivec2( x, rgl ), 0 );
	vec3 rgb  = clamp( yuvToRgb( yuv ), 0.0, 1.0 );
	fragColor = vec4( mix( src.rgb, rgb, MixAmount ), mix( src.a, 1.0, MixAmount ) );
}
`;

//=== END GENERATED

/// Which stages Shaders.cpp assembles with kCommon in front
/// (check_shaders.py holds this to Shaders.cpp's stage functions).
const STAGE_COMMON = {
  VERTEX_BODY: false,
  INTAKEV_BODY: false,
  INTAKEH_BODY: true,
  NOISE_BODY: true,
  TAPE_BODY: false,
  COMB_BODY: false,
  DOC_BODY: false,
  DISPLAY_BODY: true,
};

/// Shaders.cpp's assemble( body, common ).
const assemble = (body, common) => `${K_VERSION}\n${common ? COMMON : ''}${body}`;

//===========================================================================
// The renderer: Colourunder::InitGL and the GL half of ProcessOpenGL.
//===========================================================================

/// What the line under the canvas reports. Filled by the renderer.
const telemetry = {
  ticked: false, seconds: 0, frame: 0, standard: 0, speed: 1, generations: 1, tracking: 0,
  N: 0, Ws: 0, k: 1, drops: 0, switchLine: 0, missing: [], uniformVectors: 0,
};

/// For a driven check (AGENTS.md, "The browser demo"). `fresh()` puts the
/// renderer back to a newly instantiated plugin; `afterRender(gl, input)` runs
/// inside the frame, before the canvas is composited, so it can read it back.
const hooks = { afterRender: null, fresh: null };

function createRenderer(gl, quad) {
  telemetry.uniformVectors = gl.getParameter(gl.MAX_FRAGMENT_UNIFORM_VECTORS);

  // InitGL: every stage, as Shaders.cpp assembles it.
  const vertex = assemble(VERTEX_BODY, STAGE_COMMON.VERTEX_BODY);
  const programs = {};
  const stages = [
    ['intakev', 'INTAKEV_BODY', INTAKEV_BODY], ['intakeh', 'INTAKEH_BODY', INTAKEH_BODY],
    ['noise', 'NOISE_BODY', NOISE_BODY], ['tape', 'TAPE_BODY', TAPE_BODY],
    ['comb', 'COMB_BODY', COMB_BODY], ['doc', 'DOC_BODY', DOC_BODY], ['display', 'DISPLAY_BODY', DISPLAY_BODY],
  ];
  for (const [name, key, body] of stages) {
    try {
      programs[name] = new Program(gl, vertex, assemble(body, STAGE_COMMON[key]), name);
    } catch (error) {
      if (name === 'tape') {
        throw new GLError(`${error.message}\n\nThe tape pass declares four 96-float uniform arrays (its kernels) and 24 dropouts, about 410 fragment uniform vectors; this browser offers ${telemetry.uniformVectors}. WebGL2 only promises 224, so on this device the plugin's tape shader cannot be compiled as written, and the page will not substitute a smaller one.`);
      }
      throw error;
    }
  }

  // The plugin's buffers: RGBA32F, nearest (every read is texelFetch).
  const nearest = { filter: 'nearest' };
  const buffers = {
    columns: new PassBuffer(gl, nearest),
    intake: new PassBuffer(gl, nearest),
    work0: new PassBuffer(gl, nearest),
    work1: new PassBuffer(gl, nearest),
    work2: new PassBuffer(gl, nearest),
    noise: new PassBuffer(gl, nearest),
  };
  let lineData = null;

  let instance = new Instance();
  hooks.fresh = () => { instance = new Instance(); };

  const parameterFloats = (params) => {
    const p = new Array(10).fill(0);
    p[PT.STANDARD] = params.get('standard');
    p[PT.SPEED] = params.get('speed');
    p[PT.TRACKING] = params.get('tracking');
    p[PT.HEAD_SWITCH] = params.get('headSwitch');
    p[PT.WEAR] = params.get('wear');
    p[PT.GENERATION] = generationValue(params.get('generation'));
    p[PT.DOC] = params.get('doc');
    p[PT.CHROMA_DELAY] = params.get('chromaDelay');
    p[PT.CHROMA_NOISE] = params.get('chromaNoise');
    p[PT.MIX] = params.get('mix');
    return p.map(Math.fround);
  };

  return {
    render({ input, params, width, height, time }) {
      const W = width;
      const H = height;

      // Colourunder::SetTime, then the CPU half (model.js).
      instance.setTime(time);
      const plan = instance.planFrame(parameterFloats(params), W, H);
      const R = plan.raster;

      // Buffers, before anything is bound (PassBuffer::Ensure).
      buffers.columns.ensure(W, R.N, gl.RGBA32F);
      for (const name of ['intake', 'work0', 'work1', 'work2', 'noise']) buffers[name].ensure(R.Ws, R.N, gl.RGBA32F);
      if (plan.allocate || lineData === null) {
        if (lineData !== null) gl.deleteTexture(lineData);
        lineData = gl.createTexture();
        gl.bindTexture(gl.TEXTURE_2D, lineData);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, R.N, plan.dataRows, 0, gl.RGBA, gl.FLOAT, null);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
      }
      gl.bindTexture(gl.TEXTURE_2D, lineData);
      gl.pixelStorei(gl.UNPACK_ALIGNMENT, 4);
      gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, R.N, plan.dataRows, gl.RGBA, gl.FLOAT, plan.lineData);
      gl.bindTexture(gl.TEXTURE_2D, null);

      const textureOf = (name) => {
        if (name === 'picture') return input.texture;
        if (name === 'lineData') return lineData;
        return buffers[name].texture;
      };

      gl.disable(gl.BLEND);
      let drops = 0;
      for (const pass of plan.passes) {
        if (pass.target === 'host') {
          gl.bindFramebuffer(gl.FRAMEBUFFER, null);
          gl.viewport(0, 0, W, H);
        } else {
          buffers[pass.target].bind();
        }
        const prog = programs[pass.name].use();
        for (const [k, v] of Object.entries(pass.ints)) prog.setInt(k, v);
        for (const [k, v] of Object.entries(pass.uints)) prog.setUint(k, v);
        for (const [k, v] of Object.entries(pass.floats)) prog.set(k, v);
        for (const [k, v] of Object.entries(pass.arrays)) prog.setArray(k, v, 1);
        for (const [k, v] of Object.entries(pass.vec4s)) prog.setArray(k, v, 4);
        pass.textures.forEach((name, unit) => bindTexture(gl, unit, textureOf(name)));
        gl.activeTexture(gl.TEXTURE0);
        quad.draw();
        for (let unit = pass.textures.length - 1; unit >= 0; --unit) bindTexture(gl, unit, null);
        gl.activeTexture(gl.TEXTURE0);
        if (pass.name === 'tape') drops += pass.ints.DropCount;
      }

      telemetry.ticked = true;
      telemetry.seconds = plan.seconds;
      telemetry.frame = plan.frame;
      telemetry.standard = plan.standardIndex;
      telemetry.speed = plan.speed;
      telemetry.generations = plan.generations;
      telemetry.tracking = plan.tracking;
      telemetry.N = R.N;
      telemetry.Ws = R.Ws;
      telemetry.k = R.k;
      telemetry.drops = drops;
      telemetry.switchLine = plan.switchLine;
      // A uniform name the shader does not have is a dead control (glUniform
      // on -1 is a no-op); the kit counts them. One is expected: the noise
      // shader declares LineCount and never reads it, so every GLSL compiler
      // drops it and the plugin's own glUniform1i on it is a no-op too.
      telemetry.missing = Object.entries(programs).flatMap(([name, p]) => [...p.missing].filter((u) => !(name === 'noise' && u === 'LineCount')).map((u) => `${name}.${u}`));

      if (hooks.afterRender) hooks.afterRender(gl, input);
    },
  };
}

//===========================================================================
// The controls, read out of Colourunder::Colourunder() (model.js's
// DECLARATIONS, which check_port.sh holds to the constructor): same names,
// same groups, same order, same defaults, same dropdown elements. Absent: the
// About block.
//===========================================================================

/// Generation is FF_TYPE_INTEGER with SetParamRange( 1, 5 ), exempt from the
/// 0..1 clamp, so the plugin stores the integer itself. The kit has no
/// integer control, so -- as toner, receipt and teletext did -- it is a
/// dropdown of every value in the plugin's range; `generationValue` turns the
/// dropdown's index back into the integer.
const GENERATIONS = [];
for (let g = kGenerationsMin; g <= kGenerationsMax; g += 1) GENERATIONS.push(String(g));
const generationValue = (index) => Math.min(kGenerationsMax, Math.max(kGenerationsMin, kGenerationsMin + Math.round(index)));
const generationIndex = (value) => value - kGenerationsMin;

const IDS = ['standard', 'speed', 'tracking', 'headSwitch', 'wear', 'generation', 'doc', 'chromaDelay', 'chromaNoise', 'mix'];

const HINTS = {
  standard: {
    hint: 'PAL (625/50: 576 lines, 64 µs, the colour-under carrier at 40.125 fH = 626.953 kHz) or NTSC (525/59.94: 480 lines, 629.371 kHz). PAL’s alternating V axis and its 1H line average turn the playback phase error into a desaturation; NTSC shows it as a hue that wanders down the picture. The noise and dropouts refresh at the standard’s frame rate, 25 or 29.97 a second.',
  },
  speed: {
    hint: 'Tape speed. Luma is half amplitude at 3.0 MHz (SP), 2.76 MHz (LP, from the 250 → 230 line ratio) or 2.4 MHz (EP, an assumption no source gives); chroma stays at 0.5 MHz, about 40 lines, at every speed. The FM noise rises from SP to EP, and the chroma noise with it.',
  },
  tracking: {
    display: (v) => `${controls.tracking(v).toFixed(3)} pitch`,
    hint: 'The tracking error’s scale, in track pitches at its mean: e(t) = Tracking × (1 + 0.8 v(t)), v a seeded Catmull-Rom wander through knots 1.7 s apart, one stream per generation. At 0 the head’s crossover between two tracks of its azimuth rests in the vertical interval and nothing shows; as the error grows the noise bar (about 19 lines where the FM demodulator loses lock below 6% RF) walks out of the bottom and up the picture. The bar has no chroma, and its lines lose sync.',
  },
  headSwitch: {
    display: (v) => `${controls.headSwitchUs(v).toFixed(2)} µs`,
    hint: 'The head-to-head time-base step, 2 µs at 1. The switch lands 6.5 H before each field’s V sync (4.0 lines before the end of a PAL field’s active picture, 3.5 on NTSC, so NTSC’s cuts a line 22.38 µs in); the lines after it are displaced and the TV’s AFC pulls them back over about 12 lines. Every generation’s deck switches at the same place, so the step accumulates with Generation. A 2 µs switching transient crosses the switch line.',
  },
  wear: {
    display: (v) => `${controls.dropoutsPerFrame(v).toFixed(1)} / frame`,
    hint: 'Missing oxide: 12 v² dropouts expected a video frame (at most 24), each 1–21 µs long, on a random line; and the RF it costs, the noise ×(1 + 0.8 v). With DOC off a dropout is a white streak.',
  },
  generation: {
    hint: 'Copies of copies: the whole chain again per generation — the tape’s luma and chroma filters, the chroma delay, the noise, the tracking error (its own stream), the head switch’s step. Chroma is half amplitude near 0.35 MHz after two. FF_TYPE_INTEGER 1–5 in the plugin; a dropdown here.',
  },
  doc: {
    hint: 'The dropout compensator. On, a dropped sample takes the sample from the 1H delay line: the same place on the line before in the same field (frame line l − 2), or the one before that if it dropped out too. Off, the dropout is a white streak.',
  },
  chromaDelay: {
    display: (v) => `${controls.chromaDelayUs(v).toFixed(2)} µs`,
    hint: 'The playback filters’ group delay, 0–1 µs: colour arrives late, right of every edge. The default, 0.45 µs, is a 2nd-order Butterworth’s group delay at 0.5 MHz (√2 / 2π f).',
  },
  chromaNoise: {
    display: (v) => `σ ${controls.chromaNoise(v).toFixed(3)}, ${(controls.phaseSigmaRad(v) * 180 / Math.PI).toFixed(1)}°`,
    hint: 'The chroma noise (σ 0.04 v per channel, ×1.25 at LP, ×1.6 at EP), through the playback filter, so it blotches into horizontal streaks rather than grain; and the playback phase error, σ 15 v degrees, smooth down each field (knots every six field lines).',
  },
  mix: {
    display: (v) => `${(100 * controls.amount(v)).toFixed(0)}%`,
    hint: 'The tape against the input. Output alpha is mix( source alpha, 1, Mix ): at 1 the picture is opaque, because a tape has no alpha.',
  },
};

function declarationToKit(d, id) {
  const extra = HINTS[id] ?? {};
  const base = { id, name: d.name, group: d.group, hint: extra.hint };
  if (d.type === 'option') return { ...base, type: 'option', elements: d.elements, default: Math.round(d.default) };
  if (d.type === 'integer') return { ...base, type: 'option', elements: GENERATIONS, default: generationIndex(Math.round(d.default)) };
  if (d.type === 'boolean') return { ...base, type: 'boolean', default: d.default };
  return { ...base, type: 'standard', default: d.default, display: extra.display };
}

const PARAMS = DECLARATIONS.map((d, i) => declarationToKit(d, IDS[i]));

const demo = mountDemo({
  name: 'Colourunder',
  pluginId: 'CU01',
  kind: 'effect',
  tagline:
    'VHS’s helical-scan colour-under recording. The chroma is heterodyned down under the FM luma, so it keeps about 40 lines of resolution, arrives late and picks up band-limited blotches of noise; its playback phase error is a hue shift on NTSC and a desaturation on PAL. The head switch 6.5 lines before V sync tears the bottom lines, a tracking error walks a noise bar up the picture, and a dropout is a white streak or, with DOC on, the line above repeated. SP, LP and EP; copies of copies.',
  repo: 'https://github.com/stoatworks-labs/colourunder',

  // The stock sentence says "same maths", which is only most of the truth
  // here: the shaders are the plugin's, the numbers they run on are a port.
  blurb:
    'It is Colourunder’s own GLSL — the intake, noise, tape, comb, compensator and display passes — ported from the repository to WebGL2 and running on your GPU over the plugin’s own float line raster. Everything the plugin computes on the CPU (the kernels, the tracking error and its bar, the head switch, the dropouts, the phase error, the clock) is ported to JavaScript by hand; a script in the repository checks that port against the plugin’s own C++, but on this page you are trusting it. It runs on generated clips in this page, with the plugin’s own parameters and no install.',

  // RGBA32F line raster, as in the plugin.
  needFloat: true,
  // At Mix below 1 the output carries the source's alpha.
  showBackdrop: true,

  params: PARAMS,

  // Bars first: the colour smear, the late chroma and PAL's desaturation read
  // off them as numbers you already know. The detail sweep shows luma's band
  // edge by speed; the grid shows the head switch's tear.
  sources: ['bars', 'scene', 'detail', 'grid', 'ramp', 'spot', 'alpha', 'bars100'],

  // The plugin ships no factory presets. These are the page's own, expressed
  // entirely in the plugin's parameters and reachable with the controls.
  presets: {
    'SP, first generation': { speed: kSP },
    'EP, a long recording': { speed: kEP },
    'Third-generation copy': { generation: generationIndex(3) },
    'Fifth generation, EP': { generation: generationIndex(5), speed: kEP },
    'Tracking off (0.12)': { tracking: 0.12 },
    'Tracking badly off (0.5)': { tracking: 0.5, headSwitch: 0.8 },
    'NTSC: the hue wanders': { standard: kNTSC, chromaNoise: 1.0 },
    'PAL: the same error desaturates': { standard: kPAL, chromaNoise: 1.0 },
    'Worn tape, DOC off': { wear: 1.0, doc: 0 },
    'Worn tape, DOC on': { wear: 1.0, doc: 1 },
    'A clean deck': { tracking: 0.0, headSwitch: 0.0, wear: 0.0, chromaNoise: 0.0 },
  },

  differences: [
    'The CPU half of this plugin is a PORT, not the plugin’s own code. Colourunder computes every coefficient once a frame in C++ doubles: the nine kernels (the band edges designed with the intake’s box and the display’s gain in), the tracking error’s seeded drift and each line’s RF, bar weight and noise gain, the playback phase error and its cos and sin, the head switch’s line, step and AFC recovery, the bar’s jitter, the dropouts, the noise seeds, and every slider’s law. All of it is ported to JavaScript line for line (demo/model.js). The repository’s demo/tools/check_port.sh compiles the plugin’s own Model.cpp, Controls.cpp and Clock.cpp with the constructor and the whole of ProcessOpenGL cut out of Colourunder.cpp, GL replaced by a recorder, and compares every declaration, clock value, LineData float and uniform with the port: identical, on twelve scenarios and 594 frames, against the C++ as written and as the x86_64 slice is built. Built as the arm64 slice is (clang fuses a × b + c), 181 of 1,188 clock and tracking-error doubles differ in their last bit and no float the GPU is handed does. Nothing on this page runs that check; you are trusting it.',
    'The shaders are not a port. The version line, the kCommon block and the eight bodies are the plugin’s own GLSL, assembled as Shaders.cpp assembles them; demo/tools/check_shaders.py compares every assembled stage with what the plugin compiles and fails the repository’s verify script if a character drifts.',
    'The buffers are the plugin’s: the columns (N lines × the host width), the intake, the noise and three work buffers (N × Ws samples) are RGBA32F and read by texelFetch, and LineData is an N × 6 RGBA32F texture. WebGL2 needs EXT_color_buffer_float to render into them; the page refuses to start without it rather than fall back to 8 bits.',
    'The tape shader declares four 96-float uniform arrays (its luma, chroma and two noise kernels) and 24 dropouts: about 410 fragment uniform vectors. WebGL2 only promises 224. A browser that offers fewer than the shader needs cannot compile it, and the page then says so under the picture instead of running a smaller shader.',
    'The clock is the kit’s, in declared seconds, so the plugin’s vote on its host’s clock unit never runs. Everything downstream is the plugin’s rule, ported: seconds since the first frame in double, the video frame floor(t × 25) or floor(t × 29.97) seeding the noise, the dropouts and the phase error, the tracking error a function of the seconds alone. A paused page re-renders the same video frame, so the noise holds still; Restart sends the clock back to 0, which the plugin reads as a host clock running backwards and steps on by one nominal frame (1/60 s), so the drift carries on from where it was. The kit caps a frame at 0.1 s, so the plugin’s other jump (a gap over 0.5 s) never happens here.',
    'Generation is FF_TYPE_INTEGER, 1 to 5, in the plugin. The kit has no integer control, so it is a dropdown of the same five values.',
    'The plugin’s input is Resolume’s texture at the clip’s own size; here it is a generated clip at the composition size you choose (640 × 360 to 1920 × 1080), or your own image or video at its size. The line raster is the plugin’s rule at every size: 576 or 480 lines, and ceil(W / 1024) host pixels a sample.',
    'The picture is recorded as handed over, never multiplied by alpha (Resolume’s clips are black where they are transparent); the page’s transparent clip is premultiplied the same way. Output alpha is mix( source alpha, 1, Mix ), so at Mix 1 the output is opaque whatever is behind it.',
    'The harness-only hooks (Perturb, the quiet, forced-phase, forced-tracking and forced-dropout switches) are set to what the shipped plugin sets them to: off. The eight negative controls and the checks cutest runs through them are not on this page. The About block is absent, as on every page in this suite.',
    'The format’s figures are the plugin’s, with the plugin’s confidence: the colour-under carriers, luma’s 3 MHz at SP and the head switch’s 6.5 H are confirmed from sources; chroma’s 0.5 MHz, LP’s and EP’s luma bandwidths and the de-emphasis corner are not; every noise level, the AFC’s 12 lines, the head-switch step, the tracking geometry and the dropout rate are chosen. The repository’s AGENTS.md and ATTRIBUTIONS.md say which is which.',
    'Measured once, 2026-09-25, on one Mac: this page driven frame by frame at n / 60 against the plugin’s own harness (cutest --pipe --fps 60) on the same input frames read back from the page, at the defaults and at three other settings, at 320 × 180 and 1280 × 720, through ANGLE on Metal and through SwiftShader: every channel of every pixel within 1/255 of the plugin’s, and at most a few thousand of millions off by that one level. The details are in the repository’s AGENTS.md. Nothing on this page measures anything; the line under the picture reports what the ported clock and deck are doing.',
  ],

  createRenderer,
});

// For a driven check (AGENTS.md, "The browser demo"): the kit's state and
// redraw, the telemetry and the hooks, so a script can pause, set the clock
// to n / 60 and render one frame at a time, as `cutest --pipe --fps 60` does.
window.__colourunderDemo = { demo, telemetry, hooks, controls };

//---------------------------------------------------------------------------
// Under the canvas: a line reporting what the ported clock and deck are
// doing. Skipped in embed mode, where there is no reader.
//---------------------------------------------------------------------------
if (demo && !new URLSearchParams(window.location.search).has('embed')) {
  const stage = document.querySelector('.stage');
  if (stage) {
    const line = document.createElement('p');
    line.className = 'stage__status';
    line.id = 'telemetry';
    stage.append(line);
    const speedNames = ['SP', 'LP', 'EP'];
    setInterval(() => {
      if (!telemetry.ticked) return;
      const t = telemetry;
      const s = standardOf(t.standard);
      line.textContent =
        `${t.standard === kNTSC ? 'NTSC' : 'PAL'} ${speedNames[t.speed] ?? '?'}, ${t.generations} generation${t.generations === 1 ? '' : 's'}; `
        + `line raster ${t.N} lines × ${t.Ws} samples (${t.k} px a sample); video frame ${t.frame} at ${t.seconds.toFixed(3)} s; `
        + `tracking error ${t.tracking.toFixed(4)} pitch; ${t.drops} dropout${t.drops === 1 ? '' : 's'} this frame; `
        + `head switch on field line ${t.switchLine} of ${s.fieldActive()}`
        + `${t.missing.length ? `; UNMATCHED UNIFORMS: ${t.missing.join(', ')}` : ''}.`;
    }, 250);
  }
}
